- rhel/SPECS/pmm-server.spec
https://github.com/Percona-Lab/pmm-submodules/pull/242
> PMM-3837 Generate Swagger during the pmm-server build

- rhel/SPECS/percona-qan-api2.spec
https://github.com/Percona-Lab/pmm-submodules/pull/277
> PMM-3769 build 'percona-qan-api2' rpm  with make release

- rhel/SPECS/percona-dashboards.spec
- rhel/SPECS/percona-qan-api2.spec
- rhel/SPECS/percona-qan-app.spec
- rhel/SPECS/pmm-manage.spec
- rhel/SPECS/pmm-managed.spec
- rhel/SPECS/pmm-server.spec
- rhel/SPECS/pmm-update.spec
- rhel/SPECS/rds_exporter.spec
https://github.com/Percona-Lab/pmm-submodules/pull/293
> bump rpms version to force rpms re-build

- rhel/SPECS/pmm-managed.spec
PR title is intentionally embarrassing because we should be embarrassed.
> PMM-4114 FIXME TODO HACK version.

- rhel/SPECS/pmm-managed.spec
This reverts commit b9fc34c0174b0a44ae76d3ecf5f06a1bc77fa6c7.
> Revert "PMM-4114 FIXME TODO HACK version."

- rhel/SPECS/pmm-server.spec
> PMM-3670 Add some changes back.

- rhel/SPECS/percona-dashboards.spec
Grafana plugin must update on FB.
https://github.com/Percona-Lab/pmm-submodules/pull/386/files
> PMM-4446 Fix update panel in Grafana.

- rhel/SPECS/pmm-server.spec
https://github.com/Percona-Lab/pmm-submodules/pull/462
> PMM-4403 return 'pmm-logo.svg' file

- rhel/SPECS/grafana.spec
- rhel/SPECS/percona-qan-api2.spec
- rhel/SPECS/pmm-managed.spec
- rhel/SPECS/pmm-server.spec
- rhel/SPECS/pmm-update.spec
- rhel/SPECS/prometheus.spec
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-499/2/
https://github.com/Percona-Lab/pmm-submodules/pull/499
> PMM-4770 Bump version due to Go update.

- rhel/SPECS/grafana.spec
- rhel/SPECS/percona-qan-api2.spec
- rhel/SPECS/pmm-managed.spec
- rhel/SPECS/pmm-server.spec
- rhel/SPECS/pmm-update.spec
- rhel/SPECS/prometheus.spec
https://github.com/Percona-Lab/pmm-submodules/pull/508
> PMM-4858 Bump version due to Go update.

- rhel/SOURCES/qan-app-node_modules-1.12.0.tar.gz
- rhel/SPECS/percona-qan-app.spec
Depends on https://github.com/percona/qan-app/pull/339
> PMM-4504 build dist on packaging

- rhel/SPECS/pmm-server.spec
https://github.com/Percona-Lab/pmm-submodules/pull/554
> PMM-4907 Add installation wizard page spec.

- rhel/SOURCES/grafana-node_modules-v6.4.4.el7.tar.gz
- rhel/SOURCES/grafana-node_modules-v6.5.1.el7.tar.gz
- rhel/SPECS/grafana.spec
https://github.com/Percona-Lab/pmm-submodules/pull/561
> PMM-5087 Update Grafana to 6.5.1.

- rhel/SOURCES/grafana-5.4.5-share-panel.patch
- rhel/SPECS/grafana.spec
> PMM-5339 Some charts are not fully visible

- rhel/SPECS/prometheus.spec
> PMM-5329 Update Prometheus to version 2.15.2

- rhel/SPECS/prometheus.spec
Reverts percona/pmm-server-packaging#108
> Revert "PMM-5329 Update Prometheus to version 2.15.2"

- rhel/SPECS/prometheus.spec
> PMM-5329 Update Prometheus to version 2.16.0

- rhel/SPECS/percona-dashboards.spec
> PMM-5655 remove leftovers of Grafana plugins

- rhel/SPECS/percona-dashboards.spec
> PMM-5655 Remove leftovers of Grafana plugins fix

- rhel/SPECS/percona-dashboards.spec
Reverts percona/pmm-server-packaging#123
> Revert "PMM-5655 Remove leftovers of Grafana plugins fix"

- rhel/SPECS/alertmanager.spec
- rhel/SPECS/pmm-server.spec
> PMM-5558 Alertmanager

- rhel/SPECS/grafana.spec
- rhel/SPECS/percona-qan-api2.spec
- rhel/SPECS/pmm-managed.spec
- rhel/SPECS/pmm-update.spec
On-demand golang installation as build dep.
> PMM-5719 install golang on-demand

- rhel/SOURCES/grafana-6.7.3-share-panel.patch
- rhel/SPECS/grafana.spec
> PMM-5882 delete snapshot throws an error

- rhel/SPECS/pmm-update.spec
> Add URL for 2.6.0

- rhel/SOURCES/grafana-6.7.3-remove-update-tab.patch
- rhel/SPECS/grafana.spec
> PMM-5906 remove update page

- rhel/SPECS/pmm-server.spec
https://jira.percona.com/browse/PMM-6153
FB: https://github.com/Percona-Lab/pmm-submodules/pull/906
related PR: https://github.com/percona/pmm-server/pull/217
> PMM-6153 Add local static RSS file.

- rhel/SPECS/pmm-server.spec
> PMM-6086 CVE-2020-13379 (PMM1)

- rhel/SPECS/pmm-update.spec
https://github.com/Percona-Lab/pmm-submodules/pull/952
> Add URL for 2.9.0

- rhel/SPECS/pmm-update.spec
https://github.com/Percona-Lab/pmm-submodules/pull/952
> fix release date

- rhel/SPECS/pmm-update.spec
https://github.com/Percona-Lab/pmm-submodules/pull/997
> PMM-6417 Bump version to 2.9.1

- rhel/SPECS/pmm-update.spec
> Revert "PMM-6417 Temporary update version 2.9.2 (#151)"

- rhel/SPECS/dbaas-controller.spec
Added RPM spec for **dbaas-controller**
> PMM-6119 dbaas-controller packaging

- rhel/SPECS/prometheus.spec
> PMM-6355 upgrade prometheus version to 2.19.3

- rhel/SPECS/grafana.spec
> PMM-6360 grafana upgrade to 7.1.x build changes

- rhel/SPECS/dbaas-tools.spec
Had to remove `%doc` & `%license` as RPM automatically switches to last `%setup` directory & I can't overwrite it 
PR with FB: https://github.com/Percona-Lab/pmm-submodules/pull/1086
> PMM-6362 Add kubectl into dbaas-tools

- rhel/SPECS/pmm-update.spec
https://github.com/Percona-Lab/pmm-submodules/pull/1101
> PMM-6628 Bump version to 2.10.0

- rhel/SPECS/grafana.spec
Updates grafana spec for DBaaS features
https://github.com/Percona-Lab/pmm-submodules/pull/1075#issuecomment-687086729
> PMM-6468 Update grafana spec

- rhel/SPECS/prometheus.spec
> PMM-6557 Update Prometheus to 2.21.0

- rhel/SPECS/pmm-server.spec
> PMM-6268 upgrade angular and cve fix
